# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a11af57c43ee242d2ff06e0b0285e8e9f0cd446e6a8765e18a38c8de4cdc39239cd5a1fb63d5c86aa4cce97a6ffcae10249a5ee6ba584bce3423fe2f0005361

test:
  secret_key_base: 00f7847e23d29a2322cd88f1cd7c577d2af699ee1cfd846786d899b5481f21204df7a77d448341893f8b4469c4c096923f1cbebe4eabc4f965bbb30e556a4834

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
